import ClientComponent from "@/app/ClientComponent"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Little Moments | Profile",
  description: "Generated by create next app",
}
const RootLayout: React.FC = ({ children }: any) => {
  return <>{children}</>
}

export default RootLayout
