// "use client"
import Head from "next/head"
import "./globals.css"
import ReduxProvider from "@/services/Redux/Provider"
import type { Metadata } from "next"
import ModalProvider from "@/services/Context/ModalContext"

export const metadata: Metadata = {
  title: "Little Moments",
  description: "Generated by create next app",
}
const RootLayout: React.FC = ({ children }: any) => {
  return (
    <html lang="en">
      <Head></Head>
      <body className="font-default font-normal text-base bg-background">
        <ReduxProvider>
          <ModalProvider> {children} </ModalProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}

export default RootLayout
