import Head from "next/head"
import "./globals.css"
import ReduxProvider from "@/services/Redux/Provider"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Little Moments",
  description: "Generated by create next app",
}
const RootLayout: React.FC = ({ children }: any) => {
  return (
    <html lang="en">
      <Head>
        <title>{String(metadata.title)}</title>
        <meta name="description" content={metadata.description ?? ""} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="font-default font-normal text-base bg-background">
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  )
}

export default RootLayout
