// "use client"
import Head from "next/head"
import "./globals.css"
import ReduxProvider from "@/services/Redux/Provider"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Little Moments",
  description: "Generated by create next app",
}
const RootLayout: React.FC = ({ children }: any) => {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Passion+One&display=swap" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
        />
      </head>
      <body className="font-default font-normal text-base bg-background">
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  )
}

export default RootLayout
